### ISSUE TITLE
Clear a single cookie from a client-side

### ISSUE THREAD

**Issue by pavles6** [maticzav/nookies#133]
I have a next.js project where I have user authentication and I want to make a log out feature which would clear a single token cookie on a server. So far I have not found any approach to solve this, since i cannot pass a ctx object through getInitialProps static method, so i can use destroyCookie method. Anyone knows a workaround here how can I solve this?

**Comment by maticzav** [comment]
@pavles6 what I usually do is create a new page, `logout.js` page, for example. Because that page is dedicated to logging user out, I can use `getInitialProps` method to remove the cookie and afterwards redirect to an `index` or any other desired page.

You can see the example in one of my projects, which uses `nookies`: https://github.com/maticzav/gimb-events/blob/master/public/pages/logout.js.

Let me know if that helps. 🙂 

> PS.: A possible alternative solution is to remove the cookie using the client-side "API" (it's the same API), https://github.com/maticzav/nookies#cookies-on-the-client. You can pass in an empty object or `undefined` as a context.

**Comment by pavles6** [comment]
Sadly, this won't work for me, i manage to Router.push('/logout') whenever user clicks specific button, but firstly i had an error: TypeError: inst.render is not a function. This could be beacuse you did not include render method in your react component on /logout route. I added render method which returns null but still neither cookie got cleared, nor user got redirected.

**Comment by pavles6** [comment]
Never mind, I figured out how to make it. As you said i just passed an empty object instead of context since i haven't managed to get a context. Thanks for a help ;)
