### ISSUE TITLE
Cookie not available in getServerSideProps

### ISSUE THREAD

**Issue by zommerberg** [maticzav/nookies#335]
Hello, I am setting my httpOnly cookie in `/api/auth/login`.

```
setCookie({ res }, 'token', token, {
      httpOnly: true,
      sameSite: 'strict',
      secure: process.env.NODE_ENV === 'production',
      path: '/',
    })
```

However when I reach any route like /api/auth/refreshToken I am not able to get the cookies, they are missing, they are not available if I fetch them from getInitialProps or getServerSideProps on mount.

How to make it available in some api endpoints in the /api folder?

**Comment by zommerberg** [comment]
To be exact they are available in the /api folder but only if I fetch them from the client. If I try to access /api folder from the server, eg from getServerSideProps, only then they are not available.

**Comment by maticzav** [comment]
Hey 👋,

could you compose a small reproduction CodeSandbox? This is a very interesting problem.

**Comment by zommerberg** [comment]
Hello @maticzav ,
I have created a small example here https://github.com/zommerberg/nextjs-auth-test.
The instructions are in the app, would love to see how it is possible to access the cookies from the server, thanks!

**Comment by ThomasSwolfs** [comment]
I think this issue is similar to this one https://github.com/vercel/next.js/issues/14927.
I am also unable to retrieve cookies from the context of getServerSideProps.

**Comment by maticzav** [comment]
Hey @zommerberg,

Thank you for being so patient with my response. I think the problem might be that server doesn't act as a web browser (i.e. requests don't include headers by default) while the client does act like one. One possible solution that comes to my mind is that you forward the headers from request to the React page component and add those headers to the `axios` request.

Maybe you could even expose a "custom" fetch function as a prop, but I am not sure whether that's possible due to property parsing that Next does.
